server:
  servlet:
    encoding:
      charset: utf-8
      force: true


spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:blogExam
    username: sa
    password:
    driver-class-name: org.h2.Driver

  data:
    web:
      pageable:
        one-indexed-parameters: false
#        default-page-size: 5  페이징시 기본값 설정